function adminMoney(n){return "₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0});}
async function adminApi(path,options={}){const r=await authFetch(path,options);if(r.status===403){document.body.innerHTML='<main style="padding:80px;text-align:center;font-family:Arial"><h1>Admin access required</h1><p>This account does not have permission to view the dashboard.</p><a href="index.html">Return to store</a></main>';throw new Error("Admin access required");}if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.detail||"Admin request failed");}return r.json();}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
async function loadDashboard(){const d=await adminApi('/api/admin/dashboard');document.getElementById('metrics').innerHTML=[['Revenue',adminMoney(d.revenue)],['Orders',d.total_orders],['Customers',d.total_customers],['Low stock',d.low_stock_products]].map(x=>`<div class="metric"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');}
async function loadOrders(){const rows=await adminApi('/api/admin/orders');document.getElementById('tab-orders').innerHTML=`<h2>Recent orders</h2><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Created</th></tr></thead><tbody>${rows.map(o=>`<tr><td><strong>${esc(o.order_number)}</strong><br><small>${o.items} item(s)</small></td><td>${esc(o.customer_name)}<br><small>${esc(o.city)}</small></td><td>${adminMoney(o.total)}</td><td>${esc(o.payment_method)}<br><small>${esc(o.payment_status)}</small></td><td><select class="status-select" onchange="updateAdminOrder(${o.id},this.value)">${['Processing','Packed','Shipped','Delivered','Cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td><td>${new Date(o.created_at).toLocaleDateString('en-IN')}</td></tr>`).join('')}</tbody></table>`;}
async function updateAdminOrder(id,status){await adminApi(`/api/admin/orders/${id}`,{method:'PATCH',body:JSON.stringify({status})});await loadOrders();await loadDashboard();}
async function loadProducts(){const rows=await adminApi('/api/admin/products');document.getElementById('tab-products').innerHTML=`<h2>Products & inventory</h2><table class="admin-table"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Active</th><th>Actions</th></tr></thead><tbody>${rows.map(p=>`<tr><td><img src="${esc(p.image)}"> <strong>${esc(p.name)}</strong></td><td>${adminMoney(p.price)}</td><td><input style="width:75px" type="number" min="0" value="${p.stock}" onchange="updateStock(${p.id},this.value)"></td><td>${p.is_active?'Yes':'No'}</td><td class="admin-actions"><button onclick="archiveProduct(${p.id})" class="danger">Archive</button></td></tr>`).join('')}</tbody></table>`;}
async function updateStock(id,stock){await adminApi(`/api/admin/products/${id}`,{method:'PATCH',body:JSON.stringify({stock:Number(stock)})});await loadProducts();await loadDashboard();}
async function archiveProduct(id){if(!confirm('Archive this product?'))return;await adminApi(`/api/admin/products/${id}`,{method:'DELETE'});await loadProducts();await loadDashboard();}
async function loadCustomers(){const rows=await adminApi('/api/admin/customers');document.getElementById('tab-customers').innerHTML=`<h2>Customers</h2><table class="admin-table"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Joined</th></tr></thead><tbody>${rows.map(u=>`<tr><td>${esc(u.name)}${u.is_admin?' <small>(Admin)</small>':''}</td><td>${esc(u.email)}</td><td>${esc(u.phone||'—')}</td><td>${new Date(u.created_at).toLocaleDateString('en-IN')}</td></tr>`).join('')}</tbody></table>`;}
function switchTab(name){document.querySelectorAll('[id^="tab-"]').forEach(e=>e.classList.add('hidden'));document.getElementById('tab-'+name).classList.remove('hidden');document.querySelectorAll('.admin-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));}
document.addEventListener('DOMContentLoaded',async()=>{if(!requireAuth())return;try{const user=await adminApi('/api/auth/me');if(!user.is_admin)throw new Error('Admin access required');document.getElementById('admin-greeting').textContent=`Signed in as ${user.name} • protected admin access`;await Promise.all([loadDashboard(),loadOrders(),loadProducts(),loadCustomers()]);}catch(e){alert(e.message);location.href='index.html';return;}document.querySelectorAll('.admin-tabs button').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));document.getElementById('refresh-admin').onclick=()=>Promise.all([loadDashboard(),loadOrders(),loadProducts(),loadCustomers()]);document.getElementById('admin-logout').onclick=()=>{clearAuthSession();location.href='index.html'};document.getElementById('product-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const payload={name:f.get('name'),slug:f.get('slug'),category:f.get('category'),price:Number(f.get('price')),old_price:f.get('old_price')?Number(f.get('old_price')):null,tag:f.get('tag')||null,image:f.get('image'),stock:Number(f.get('stock')),reviews:f.get('reviews')||'0',rating:Number(f.get('rating')||0),description:f.get('description')||'',is_active:true};try{await adminApi('/api/admin/products',{method:'POST',body:JSON.stringify(payload)});e.target.reset();document.getElementById('product-message').textContent='Product created ✓';await loadProducts();await loadDashboard();switchTab('products')}catch(err){document.getElementById('product-message').textContent=err.message;}});});
