document.addEventListener("DOMContentLoaded",()=>{
 const target=document.getElementById("cart-items");if(!target)return;
 const renderGuest=()=>{const cart=getCart();if(!cart.length){target.innerHTML='<div class="empty-state"><h2>Your bag is empty.</h2><a class="btn btn-primary" href="shop.html">Start shopping</a></div>';updateCartCount();return;}let total=0;const rows=cart.map(i=>{const p=PRODUCTS.find(x=>x.id===i.id);if(!p)return "";total+=p.price*i.qty;return `<div class="cart-row"><div><strong>${p.name}</strong><span>${money(p.price)} × ${i.qty}</span></div><div class="qty-controls"><button onclick="changeQty(${p.id},-1)">−</button><strong>${i.qty}</strong><button onclick="changeQty(${p.id},1)">+</button></div><strong>${money(p.price*i.qty)}</strong></div>`}).join("");target.innerHTML=`<div class="cart-list">${rows}</div><aside class="summary-card"><h2>Summary</h2><p>Total <strong>${money(total)}</strong></p><a class="btn btn-primary" href="checkout.html">Checkout</a></aside>`;updateCartCount();};
 const renderServer=async()=>{try{const r=await authFetch("/api/cart");const data=await r.json();if(!r.ok)throw new Error(data.detail||"Could not load cart");window.serverCart=data;updateServerCartCount(data);if(!data.items.length){target.innerHTML='<div class="empty-state"><h2>Your bag is empty.</h2><a class="btn btn-primary" href="shop.html">Start shopping</a></div>';return;}const rows=data.items.map(i=>`<div class="cart-row"><div><strong>${i.product.name}</strong><span>${money(i.product.price)} × ${i.quantity}</span></div><div class="qty-controls"><button onclick="serverQty(${i.product.id},${i.quantity-1})">−</button><strong>${i.quantity}</strong><button onclick="serverQty(${i.product.id},${i.quantity+1})">+</button></div><div><strong>${money(i.line_total)}</strong><button class="text-link cart-remove" onclick="removeServer(${i.product.id})">Remove</button></div></div>`).join("");target.innerHTML=`<div class="cart-list">${rows}</div><aside class="summary-card"><h2>Summary</h2><p>${data.item_count} item(s)</p><p>Total <strong>${money(data.total)}</strong></p><a class="btn btn-primary" href="checkout.html">Checkout</a></aside>`;}catch(e){target.innerHTML=`<div class="empty-state"><h2>Could not load your bag.</h2><p>${e.message}</p></div>`;}};
 window.changeQty=(id,d)=>{const c=getCart(),i=c.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)c.splice(c.indexOf(i),1);saveCart(c);renderGuest();};
 window.serverQty=async(id,qty)=>{if(qty<=0)return removeServer(id);const r=await authFetch(`/api/cart/items/${id}`,{method:"PATCH",body:JSON.stringify({quantity:qty})});const data=await r.json();if(!r.ok){alert(data.detail||"Could not update quantity");return;}window.serverCart=data;updateServerCartCount(data);renderServer();};
 window.removeServer=async(id)=>{const r=await authFetch(`/api/cart/items/${id}`,{method:"DELETE"});const data=await r.json();if(!r.ok){alert(data.detail||"Could not remove item");return;}window.serverCart=data;updateServerCartCount(data);renderServer();};
 (async()=>{if(typeof getAuthToken==="function"&&getAuthToken())await renderServer();else await (window.productsReady||Promise.resolve()).then(renderGuest);})();
});
